name: Deploy Production

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Deploy Production to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: simple-typing
          directory: ./build/client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  remove-merged-branch:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Delete Branches
        run: |
          git branch -r --merged=main | grep -vE '^\s*origin/(main$|develop$|HEAD$)' | sed 's/origin\///' | xargs git push --delete origin
